### ISSUE TITLE
模板的问题，让我在文章中用MD语法时出现灰色前缀字号

### ISSUE THREAD

**Issue by clien9025** [xzhuz/halo-theme-xue#106]
## 概述

去掉博客文章的灰色前缀字号（h1,h2,h3,h4,h5.....等等）

## 动机

  因为这样真的很影响我博客的阅读，以至于在有时候博客文章采用的markdown语法书写时，标号太小导致文章中的有序排列的序号和灰色前缀字号重合，导致超级影响阅读。

## 详细解释
我在写留言板的时候，发现写完留言板之后，在留言板发布的页面上有个[模板]选项（默认是 link），我点选[link]之后就没有像我其他文章那样的灰色前缀字号出现了，蛮好用的。

我希望在[文章] --> [写文章] 之后发布的时候，发布页面也有这样一个模板选项，让我来勾选 [link] 选项，用来消除灰色前缀字号

**Comment by xzhuz** [comment]
如果你想取消标题前面的字号，只能通过自定义样式来实现。
```css
.md-content h1:before ,.md-content h2:before, .md-content h3:before, .md-content h4:befoer, .md-content h5:before, .md-content h6:before{
    content: '';
    bottom: .18rem;
}
```

**Comment by clien9025** [comment]
那把这个样式放在哪里呢？还请大大指点下~

**Comment by xzhuz** [comment]
![image](https://user-images.githubusercontent.com/23736683/100409537-167e9c00-30a7-11eb-8e0a-358e1da3ce56.png)
这里就可以，但是上面的样式需要用 `<style></style>`包裹起来

**Comment by clien9025** [comment]
> 这里就可以，但是上面的样式需要用 `<style></style>`包裹起来
好的，俺来试试。

**Comment by clien9025** [comment]
```css
<style>
.md-content h1: before, .md-content h2: before, .md-content h3: before, .md-content h4: before, .md-content h5 :before, .md-content h6: before,
{
    content: '';
    bottom: .18rem;
}
</style>
```
这样的代码是正确的嘛？
俺怎么测试了下，前缀还是在的，呜呜呜~
