### ISSUE TITLE
如何去掉首页的热门文章的展示

### ISSUE THREAD

**Issue by haodedong** [xzhuz/halo-theme-xue#82]
您好，我找了很久都没有找到如何去掉首页的热门文章的展示。您可以指导一下嘛

**Comment by xzhuz** [comment]
你是既要使用列表样式又不要热门博客是吧

**Comment by xzhuz** [comment]
![image](https://user-images.githubusercontent.com/23736683/96145468-cf45ad00-0f37-11eb-91c8-a6cf1e3e3405.png)

可以在这个地方加上下面代码：
```css
<style type="text/css">
   .popular-posts {
      display:none !important;
   }
</style>
```
